const DOOR_SUPERVISOUR_LICENCE_ID = 12;
const CCTV_LICENCE_ID = 13;
const SECURITY_GUARDING_LICENCE_ID = 44;
const CLOSE_PROTECTION_LICENCE_ID = 29;

export {
  DOOR_SUPERVISOUR_LICENCE_ID,
  CCTV_LICENCE_ID,
  SECURITY_GUARDING_LICENCE_ID,
  CLOSE_PROTECTION_LICENCE_ID,
};
