// Staffing
export const SET_SCREEN_TO_SHOW_ON_STAFFING = "SET_SCREEN_TO_SHOW_ON_STAFFING";
export const SET_JOBS_POSTED_BY_USER = "SET_JOBS_POSTED_BY_USER";
export const SET_FILTER_FOR_JOB_LIST = "SET_FILTER_FOR_JOB_LIST";
export const SET_DATE_ORDER_FOR_JOB_LIST = "SET_DATE_ORDER_FOR_JOB_LIST";
export const SET_SEARCH_KEYWORD_FOR_JOB_LIST =
  "SET_SEARCH_KEYWORD_FOR_JOB_LIST";
export const SET_PAGINATION_FOR_JOB_LIST = "SET_PAGINATION_FOR_JOB_LIST";
export const SET_CURRENT_PAGE_FOR_JOB_LIST = "SET_CURRENT_PAGE_FOR_JOB_LIST";
export const SET_TOTAL_PAGES_FOR_JOB_LIST = "SET_TOTAL_PAGES_FOR_JOB_LIST";
export const SET_JOB_TO_BE_SHOWN_IN_APPLICANT_TAB =
  "SET_JOB_TO_BE_SHOWN_IN_APPLICANT_TAB";
export const SET_SELECTED_JOB_APPLICANTS = "SET_SELECTED_JOB_APPLICANTS";
export const SET_SELECTED_JOB_APPLICANTS_SHIMMER =
  "SET_SELECTED_JOB_APPLICANTS_SHIMMER";
export const SET_DID_USER_CLICKED_A_JOB = "SET_DID_USER_CLICKED_A_JOB";
export const SET_LATEST_JOB_ID = "SET_LATEST_JOB_ID";
export const SET_PAGINATION_FOR_APPLICANT_LIST =
  "SET_PAGINATION_FOR_APPLICANT_LIST";
export const SET_CURRENT_PAGE_FOR_APPLICANT_LIST =
  "SET_CURRENT_PAGE_FOR_APPLICANT_LIST";
export const SET_TOTAL_PAGES_FOR_APPLICANT_LIST =
  "SET_TOTAL_PAGES_FOR_APPLICANT_LIST";
export const SET_FILTER_FOR_APPLICANT_LIST = "SET_FILTER_FOR_APPLICANT_LIST";
export const SET_DATE_ORDER_FOR_APPLICANT_LIST =
  "SET_DATE_ORDER_FOR_APPLICANT_LIST";
export const SET_SEARCH_KEYWORD_FOR_APPLICANT_LIST =
  "SET_SEARCH_KEYWORD_FOR_APPLICANT_LIST";
export const SET_SWP_PROFILE_TO_BE_SHOWN = "SET_SWP_PROFILE_TO_BE_SHOWN";
export const SET_SWP_PROFILE_SHIMMER = "SET_SWP_PROFILE_SHIMMER";
export const RESET_STAFFING_REDUCER = "RESET_STAFFING_REDUCER";
export const SET_SWP_PROFILE_WINDOW_STATUS = "SET_SWP_PROFILE_WINDOW_STATUS";
export const SET_SHOW_JOB_PREVIEW = "SET_SHOW_JOB_PREVIEW";
export const SET_ACTIVE_STEP_FOR_CLOSE_JOB_DISCARD =
  "SET_ACTIVE_STEP_FOR_CLOSE_JOB_DISCARD";
export const SET_RADIO_FOR_JOB_DISCARD = "SET_RADIO_FOR_JOB_DISCARD";
export const SET_CHECKBOX_LIST_FOR_CLOSE_JOB_DISCARD =
  "SET_CHECKBOX_LIST_FOR_CLOSE_JOB_DISCARD";
export const SET_YES_SCREEN_QUESTION_FOR_CLOSE_JOB_DISCARD =
  "SET_YES_SCREEN_QUESTION_FOR_CLOSE_JOB_DISCARD";
export const SET_NO_SCREEN_QUESTION_FOR_CLOSE_JOB_DISCARD =
  "SET_NO_SCREEN_QUESTION_FOR_CLOSE_JOB_DISCARD";
export const SET_SELECTED_JOB_ID_FOR_CLOSE_JOB_DISCARD =
  "SET_SELECTED_JOB_ID_FOR_CLOSE_JOB_DISCARD";
export const SET_SHOW_GOOGLE_MAP_FOR_GOOGLE = "SET_SHOW_GOOGLE_MAP_FOR_GOOGLE";
export const SET_SHOW_GOOGLE_MAP_FOR_LOQATE = "SET_SHOW_GOOGLE_MAP_FOR_LOQATE";
export const SET_SELECTED_JOB_NAME_FOR_CLOSE_JOB_DISCARD =
  "SET_SELECTED_JOB_NAME_FOR_CLOSE_JOB_DISCARD";
export const SET_JOB_DESCRIPTION_DATA = "SET_JOB_DESCRIPTION_DATA";
export const SET_CLICKED_SWP_PROFILE_STATUS = "SET_CLICKED_SWP_PROFILE_STATUS";
export const SET_SWP_PROFILE_NOTES = "SET_SWP_PROFILE_NOTES";
export const SET_SWP_PROFILE_INDEX = "SET_SWP_PROFILE_INDEX";
export const SET_SALARY_WORK_HOUR_PER_WEEK = "SET_SALARY_WORK_HOUR_PER_WEEK";
export const SET_COMPANY_NAME_SUGGESTIONS = "SET_COMPANY_NAME_SUGGESTIONS";
export const SET_INVITE_APPLICANTS = "SET_INVITE_APPLICANTS";
export const SET_JOB_HEADER_STATS = "SET_JOB_HEADER_STATS";
export const SET_APPLICANT_IN_STATE_FOR_FEEDBACK =
  "SET_APPLICANT_IN_STATE_FOR_FEEDBACK";
export const SET_LAST_JOB_CONNECT = "SET_LAST_JOB_CONNECT";
export const SET_NEXT_CANDIDATE_STATUS = "SET_NEXT_CANDIDATE_STATUS";
export const SET_CLICKED_JOB_ID_FOR_EDIT = "SET_CLICKED_JOB_ID_FOR_EDIT";

// jobPostReducer
export const RESET_JOBPOST_REDUCER = "RESET_JOBPOST_REDUCER";
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const SET_JOB_TITLE = "SET_JOB_TITLE";
export const SET_JOB_DESCRIPTION_TITLES = "SET_JOB_DESCRIPTION_TITLES";
export const SET_JOB_DESCRIPTION_TEMPLATE = "SET_JOB_DESCRIPTION_TEMPLATE";
export const SET_TYPE_OF_EMPLOYMENT = "SET_TYPE_OF_EMPLOYMENT";
export const SET_SIA_LICENSE = "SET_SIA_LICENSE";
export const SET_RADIO = "SET_RADIO";
export const SET_CONTRACT = "SET_CONTRACT";
export const SET_VENUE_TYPE = "SET_VENUE_TYPE";
export const SET_VENUE_TYPE_OTHER_VALUE = "SET_VENUE_TYPE_OTHER_VALUE";
export const SET_IMMEDIATE_HIRING = "SET_IMMEDIATE_HIRING";
export const SET_EDITOR = "SET_EDITOR";
export const SET_WILL_REPORT_TO_SPECIFIC_ADDRESS =
  "SET_WILL_REPORT_TO_SPECIFIC_ADDRESS";
export const SET_WILL_NOT_REPORT_TO_CITY = "SET_WILL_NOT_REPORT_TO_CITY";
export const SET_WILL_NOT_REPORT_TO_POST_CODE =
  "SET_WILL_NOT_REPORT_TO_POST_CODE";
export const SET_CENTER_FOR_MAP_GOOGLE = "SET_CENTER_FOR_MAP_GOOGLE";
export const SET_CENTER_FOR_MAP_LOQATE = "SET_CENTER_FOR_MAP_LOQATE";
export const SET_WILL_REPORT_TO_WORK_POST_CODE =
  "SET_WILL_REPORT_TO_WORK_POST_CODE";
export const SET_WILL_REPORT_TO_WORK_CITY = "SET_WILL_REPORT_TO_WORK_CITY";
export const SET_WILL_REPORT_TO_WORK_ADDRESS_ONE =
  "SET_WILL_REPORT_TO_WORK_ADDRESS_ONE";
export const SET_WILL_REPORT_TO_WORK_ADDRESS_TWO =
  "SET_WILL_REPORT_TO_WORK_ADDRESS_TWO";
export const SET_WILL_REPORT_TO_WORK_FIELDS_SHOW_HIDE =
  "SET_WILL_REPORT_TO_WORK_FIELDS_SHOW_HIDE";
export const SET_LOQATE_RESPONSE_FOR_TEXT = "SET_LOQATE_RESPONSE_FOR_TEXT";
export const SET_LOQATE_RESPONSE_FOR_ID = "SET_LOQATE_RESPONSE_FOR_ID";
export const SET_SALARY_VALUE = "SET_SALARY_VALUE";
export const SET_SALARY_TYPE = "SET_SALARY_TYPE";
export const SET_SALARY_RANGE_MIN = "SET_SALARY_RANGE_MIN";
export const SET_SALARY_RANGE_MAX = "SET_SALARY_RANGE_MAX";
export const SET_SALARY_VALUE_PER_UNIT = "SET_SALARY_VALUE_PER_UNIT";
export const SET_SALARY_BENEFITS = "SET_SALARY_BENEFITS";
export const SET_SETTINGS_EMAIL = "SET_SETTINGS_EMAIL";
export const SET_DISCARD_MODAL_FOR_JOB_POST = "SET_DISCARD_MODAL_FOR_JOB_POST";
export const SET_DISCARD_LINK_FOR_MODAL = "SET_DISCARD_LINK_FOR_MODAL";
export const SET_JOB_TITLE_SUGGESTION = "SET_JOB_TITLE_SUGGESTION";
export const SET_JOB_REF_NUMBER = "SET_JOB_REF_NUMBER";
export const SET_SHIFT_SCHEDULE = "SET_SHIFT_SCHEDULE";
export const SET_SHIFT_TIMING = "SET_SHIFT_TIMING";
export const SET_AVALIBLE_CONNECTS = "SET_AVALIBLE_CONNECTS";
export const SET_CLIENT_SECRET = "SET_CLIENT_SECRET";
export const SET_PAYMENT_INTENT = "SET_PAYMENT_INTENT";
export const SET_JOB_PRICE = "SET_JOB_PRICE";
export const SET_JOB_PRICE_VAT = "SET_JOB_PRICE_VAT";
export const SET_SELECTED_LOCATION_FROM_GOOGLE =
  "SET_SELECTED_LOCATION_FROM_GOOGLE";
export const SET_DRAFT_LATEST_JOB_ID = "SET_DRAFT_LATEST_JOB_ID";
export const SET_USER_IN_JOB_POSTING_FLOW = "SET_USER_IN_JOB_POSTING_FLOW";
export const SET_AVAILABLE_BOOST_COUNT = "SET_AVAILABLE_BOOST_COUNT";

export const SET_AVAILABLE_FOR_TEAM = "SET_AVAILABLE_FOR_TEAM";
export const SET_SAVE_JOB_AS_TEMPLATE = "SET_SAVE_JOB_AS_TEMPLATE";
export const SET_UPDATE_JOB_TEMPLATE = "SET_UPDATE_JOB_TEMPLATE";
export const SET_TEMPLATE_ID_FOR_JOB_UPDATE = "SET_TEMPLATE_ID_FOR_JOB_UPDATE";
export const SET_TEMPLATE_NAME = "SET_TEMPLATE_NAME";
export const SET_FROM_JOB_TEMPLATE = "SET_FROM_JOB_TEMPLATE";
export const SET_JOB_DRAFT = "SET_JOB_DRAFT";
export const FETCH_JOBS = "FETCH_JOBS";
export const WEBSITE_LINK = "WEBSITE_LINK";

// coursesReducer
export const GET_COURSES = "GET_COURSES";
export const SET_COURSES = "SET_COURSES";
export const GET_COURSES_PAGINATION_LINKS = "GET_COURSES_PAGINATION_LINKS";
export const SET_COURSES_PAGINATION_LINKS = "SET_COURSES_PAGINATION_LINKS";
export const SET_UPCOMING_COURSES = "SET_UPCOMING_COURSES";
export const SET_UPCOMING_COURSES_PAGINATION_LINKS =
  "SET_UPCOMING_COURSES_PAGINATION_LINKS";
export const SET_SEARCH_COURSES = "SET_SEARCH_COURSES";
export const SET_SEARCH_COURSES_PAGINATION_LINKS =
  "SET_SEARCH_COURSES_PAGINATION_LINKS";
export const SET_SEARCH_POSTCODE = "SET_SEARCH_POSTCODE";
export const RESER_COURSE_REDUCER = "RESER_COURSE_REDUCER";
export const SET_PAST_COURSES_STATE = "SET_PAST_COURSES_STATE";
export const SET_UPCOMING_COURSES_STATE = "SET_UPCOMING_COURSES_STATE";
export const SET_PAST_SELECTED_COURSES = "SET_PAST_SELECTED_COURSES";
export const SET_UPCOMING_SELECTED_COURSES = "SET_UPCOMING_SELECTED_COURSES";
export const SET_DASHBOARD_PAST_COURSES = "SET_DASHBOARD_PAST_COURSES";
export const SET_DASHBOARD_UPCOMING_COURSES = "SET_DASHBOARD_UPCOMING_COURSES";
export const SET_PAST_RECORDS_LAST_PAGE = "SET_PAST_RECORDS_LAST_PAGE";
export const SET_UPCOMING_RECORDS_LAST_PAGE = "SET_UPCOMING_RECORDS_LAST_PAGE";
export const SET_PAST_CURRENT_PAGE = "SET_PAST_CURRENT_PAGE";
export const SET_UPCOMING_CURRENT_PAGE = "SET_UPCOMING_CURRENT_PAGE";

// commonReducer
export const GET_IS_REQUEST_LOADER = "GET_IS_REQUEST_LOADER";
export const SET_IS_REQUEST_LOADER = "SET_IS_REQUEST_LOADER";
export const SET_IS_NAVBAR_OPEN = "SET_IS_NAVBAR_OPEN";
export const SET_IS_MODEL_OPEN = "SET_IS_MODEL_OPEN";
export const SET_IS_MODEL_LINK = "SET_IS_MODEL_LINK";
export const RESET_COMMON_REDUCER = "RESET_COMMON_REDUCER";
export const SET_SIGNUP_NAME = "SET_SIGNUP_NAME";
export const SET_THANK_YOU_PAGE_SHOW = "SET_THANK_YOU_PAGE_SHOW";
export const SET_COMPONENT_SHAKE_ON_PAGE_ONE =
  "SET_COMPONENT_SHAKE_ON_PAGE_ONE";
export const SET_SCREEN_TO_BE_SHOWN_ON_LOGIN =
  "SET_SCREEN_TO_BE_SHOWN_ON_LOGIN";
export const SET_SCREEN_TO_BE_SHOWN_ON_SIGNUP =
  "SET_SCREEN_TO_BE_SHOWN_ON_SIGNUP";
export const SET_CONTACT_NAME_FOR_SIGNUP = "SET_CONTACT_NAME_FOR_SIGNUP";
export const SET_EMAIL_ADDRESS_FOR_SIGNUP = "SET_EMAIL_ADDRESS_FOR_SIGNUP";
export const SET_PHONE_NUMBER_FOR_SIGNUP = "SET_PHONE_NUMBER_FOR_SIGNUP";
export const SET_COMPANY_SIZE_FOR_SIGNUP = "SET_COMPANY_SIZE_FOR_SIGNUP";
export const SET_COMPANY_NAME_FOR_SIGNUP = "SET_COMPANY_NAME_FOR_SIGNUP";
export const SET_COMPANY_ADDRESS_FOR_SIGNUP = "SET_COMPANY_ADDRESS_FOR_SIGNUP";
export const SET_COMPANY_ADDRESS_ONE_FOR_SIGNUP =
  "SET_COMPANY_ADDRESS_ONE_FOR_SIGNUP";
export const SET_COMPANY_ADDRESS_TWO_FOR_SIGNUP =
  "SET_COMPANY_ADDRESS_TWO_FOR_SIGNUP";
export const SET_COMPANY_CITY_FOR_SIGNUP = "SET_COMPANY_CITY_FOR_SIGNUP";
export const SET_COMPANY_POST_FOR_SIGNUP = "SET_COMPANY_POST_FOR_SIGNUP";
export const SET_TERMS_FOR_SIGNUP = "SET_TERMS_FOR_SIGNUP";
export const SET_COMPANY_NUMBER_FOR_SIGNUP = "SET_COMPANY_NUMBER_FOR_SIGNUP";
export const SET_INVALID_PASSCODE = "SET_INVALID_PASSCODE";
// export const SET_ACCOUNT_APPROVAL = "SET_ACCOUNT_APPROVAL";
// export const SET_HAS_CONGRATULATED = "SET_HAS_CONGRATULATED";
// export const SET_SHOW_CONGRATULATION_MODAL = "SET_SHOW_CONGRATULATION_MODAL";

// userReducer
export const GET_USER_TOKEN = "GET_USER_TOKEN";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const GET_USER_TOKEN_TYPE = "GET_USER_TOKEN_TYPE";
export const SET_USER_TOKEN_TYPE = "SET_USER_TOKEN_TYPE";
export const SET_IS_USER_LOGIN = "SET_IS_USER_LOGIN";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_NAME = "SET_USER_NAME";
export const SET_DECISION_MAKER_FIRST_NAME = "SET_DECISION_MAKER_FIRST_NAME";
export const SET_DECISION_MAKER_LAST_NAME = "SET_DECISION_MAKER_LAST_NAME";
export const SET_USER_EMAIL = "SET_USER_EMAIL";
export const SET_USER_MOBILE_NUMBER = "SET_USER_MOBILE_NUMBER";
export const SET_ADDRESS1 = "SET_ADDRESS1";
export const SET_ADDRESS2 = "SET_ADDRESS2";
export const SET_CITY = "SET_CITY";
export const RESET_USER_DATA_REDUCER = "RESET_USER_DATA_REDUCER";
export const SET_USER_POSTCODE = "SET_USER_POSTCODE";
export const SET_IS_DISCOUNT_ENABLED = "SET_IS_DISCOUNT_ENABLED";
export const SET_DISCOUNT_ON_COURSE_BOOKING = "SET_DISCOUNT_ON_COURSE_BOOKING";
export const SET_NO_OF_BOOKINGS_TO_AVAIL_DISCOUNT =
  "SET_NO_OF_BOOKINGS_TO_AVAIL_DISCOUNT";
export const SET_IS_BANK_TRANSFER_AVALIBLE = "SET_IS_BANK_TRANSFER_AVALIBLE";
export const SET_IS_USER_ACCOUNT_VERIFIED = "SET_IS_USER_ACCOUNT_VERIFIED";
export const SET_IS_NEWS_MODAL_DISABLED = "SET_IS_NEWS_MODAL_DISABLED";
export const SET_IS_CV_SEARCH_AVALIBLE = "SET_IS_CV_SEARCH_AVALIBLE";
export const SET_IS_ONBOARDING_FEEDBACK_DONE =
  "SET_IS_ONBOARDING_FEEDBACK_DONE";
export const SET_IS_ONBOARDING_TOUR_DONE = "SET_IS_ONBOARDING_TOUR_DONE";
export const SET_IS_ONBOARDING_FEEDBACK_MODAL =
  "SET_IS_ONBOARDING_FEEDBACK_MODAL";
export const SET_IS_ONBOARDING_TOUR_MODAL = "SET_IS_ONBOARDING_TOUR_MODAL";

// bookingReducer
export const SET_BOOKING_ACTIVE_STEP = "SET_BOOKING_ACTIVE_STEP";
export const SET_POSTCODE = "SET_POSTCODE";
export const SET_SELECTED_COURSE_ID = "SET_SELECTED_COURSE_ID";
export const SET_SELECTED_COURSE_NAME = "SET_SELECTED_COURSE_NAME";
export const SET_NUMBER_OF_SEATS = "SET_NUMBER_OF_SEATS";
export const SET_SELECTED_LOCATION_OBJECT = "SET_SELECTED_LOCATION_OBJECT";
export const SET_LOCATION_ID = "SET_LOCATION_ID";
export const SET_LOCATION_NAME = "SET_LOCATION_NAME";
export const SET_ATTENDEES = "SET_ATTENDEES";
export const SET_ATTENDEES_SHOW_ERROR = "SET_ATTENDEES_SHOW_ERROR";
export const SET_SESSION_ID = "SET_SESSION_ID";
export const SET_PAYMENT_INTENT_ID = "SET_PAYMENT_INTENT_ID";
export const RESET_BOOKING_REDUCER = "RESET_BOOKING_REDUCER";
export const SET_PCA_RESPONSE = "SET_PCA_RESPONSE";
export const SET_LAST_PAGE_NO_OF_BOOKING_FILTER_PG2 =
  "SET_LAST_PAGE_NO_OF_BOOKING_FILTER_PG2";
export const SET_NO_OF_SEATS_ERROR = "SET_NO_OF_SEATS_ERROR";
export const SET_SCREEB_TO_BE_LOADED_ON_STEP5_CHECKOUT =
  "SET_SCREEB_TO_BE_LOADED_ON_STEP5_CHECKOUT";
export const SET_STEP5_RADIO_BTN_VALUE = "SET_STEP5_RADIO_BTN_VALUE";
export const SET_STEP5_CHECKBOX_BTN_VALUE = "SET_STEP5_CHECKBOX_BTN_VALUE";
export const SET_DID_USER_PLACED_THE_ORDER = "SET_DID_USER_PLACED_THE_ORDER";
export const SET_SUB_TOTAL_FOR_PAYMENT = "SET_SUB_TOTAL_FOR_PAYMENT";
export const SET_UNLIMITTED_RETAKES_TOTAL_FOR_PAYMENT =
  "SET_UNLIMITTED_RETAKES_TOTAL_FOR_PAYMENT";
export const SET_EFAW_TOTAL_FOR_PAYMENT = "SET_EFAW_TOTAL_FOR_PAYMENT";
export const SET_DISCOUNT_FOR_PAYMENT = "SET_DISCOUNT_FOR_PAYMENT";
export const SET_TOTAL_BILL_TOTAL_FOR_PAYMENT =
  "SET_TOTAL_BILL_TOTAL_FOR_PAYMENT";
export const SET_NO_OF_BOOKINGS_FOR_FIRST_AID_FOR_PAYMENT =
  "SET_NO_OF_BOOKINGS_FOR_FIRST_AID_FOR_PAYMENT";
export const SET_NO_OF_BOOKINGS_FOR_UNLIMITED_RETAKES_FOR_PAYMENT =
  "SET_NO_OF_BOOKINGS_FOR_UNLIMITED_RETAKES_FOR_PAYMENT";
export const SET_BOOKING_REF_NO = "SET_BOOKING_REF_NO";
export const SET_SHOULD_SLIDER_SHAKE_ON_STEP_ONE =
  "SET_SHOULD_SLIDER_SHAKE_ON_STEP_ONE";
export const SET_USER_PO_NUMBER = "SET_USER_PO_NUMBER";
export const SET_VIRTUAL_EVENT = "SET_VIRTUAL_EVENT";
export const SET_CLIENT_SECRET_FOR_BOOKING = "SET_CLIENT_SECRET_FOR_BOOKING";

//Chat
export const RESET_CHAT_REDUCER = "RESET_CHAT_REDUCER";
export const SET_SOCKET_CONNECTION_STATUS = "SET_SOCKET_CONNECTION_STATUS";
export const SET_CHAT_SHOW_CHANNEL = "SET_CHAT_SHOW_CHANNEL";
export const SET_CHAT_GROUP_ID_CHANNEL = "SET_CHAT_GROUP_ID_CHANNEL";
export const SET_CHAT_USER_NAME_CHANNEL = "SET_CHAT_USER_NAME_CHANNEL";
export const SET_CHAT_USER_JOBS_CHANNEL = "SET_CHAT_USER_JOBS_CHANNEL";
export const SET_CHAT_USER_PROFILE_CHANNEL = "SET_CHAT_USER_PROFILE_CHANNEL";
export const SET_CHAT_USER_ONLINE_STATUS_CHANNEL =
  "SET_CHAT_USER_ONLINE_STATUS_CHANNEL";
export const SET_CHAT_IS_COMMING_FORM_STAFFING_CHANNEL =
  "SET_CHAT_IS_COMMING_FORM_STAFFING_CHANNEL";
export const SET_CHAT_HAS_DONE_CHAT_BEFORE_CHANNEL =
  "SET_CHAT_HAS_DONE_CHAT_BEFORE_CHANNEL";
export const SET_UNREAD_MESSAGE_COUNT = "SET_UNREAD_MESSAGE_COUNT";
export const SET_IS_FILE_UPLOADING = "SET_IS_FILE_UPLOADING";
export const SET_SHOW_CHANNEL_AND_HIDECHANNEL_LIST_ON_MOBILE =
  "SET_SHOW_CHANNEL_AND_HIDECHANNEL_LIST_ON_MOBILE";
export const SET_IMAGE_TO_BE_SHOWN_IN_MSG_IMG_PREVIEW_MODAL =
  "SET_IMAGE_TO_BE_SHOWN_IN_MSG_IMG_PREVIEW_MODAL";
export const SET_IMG_MSG_MODAL_PREVIEW = "SET_IMG_MSG_MODAL_PREVIEW";
export const SET_IS_CHANNEL_BLOCKED = "SET_IS_CHANNEL_BLOCKED";
export const SET_IS_TYPING = "SET_IS_TYPING";
export const SET_IS_CURRENT_PAGE = "SET_IS_CURRENT_PAGE";
export const SET_IS_SKIP = "SET_IS_SKIP";

//Global Chat
export const RESET_GLOBAL_CHAT_REDUCER = "RESET_GLOBAL_CHAT_REDUCER";
export const SET_SHOW_GLOBALE_CHAT_CHANNEL_LIST =
  "SET_SHOW_GLOBALE_CHAT_CHANNEL_LIST";
export const SET_GLOBALE_CHANNEL_ONE = "SET_GLOBALE_CHANNEL_ONE";
export const SET_GLOBALE_CHANNEL_TWO = "SET_GLOBALE_CHANNEL_TWO";

//CV Search
export const RESET_CV_SEARCH_REDUCER = "RESET_CV_SEARCH_REDUCER";
export const SET_LICENSE_TYPE = "SET_LICENSE_TYPE";
export const SET_LOCATION = "SET_LOCATION";
export const SET_DISTANCE = "SET_DISTANCE";
export const SET_VIDEO_ONLY_CHECK = "SET_VIDEO_ONLY_CHECK";
export const SET_SHOW_CV_SEARCH_PROFILE = "SET_SHOW_CV_SEARCH_PROFILE";
export const SET_SWP_PROFILE_ID = "SET_SWP_PROFILE_ID";
export const SET_LATITUDE_FOR_CV_SEARCH = "SET_LATITUDE_FOR_CV_SEARCH";
export const SET_LONGITUDE_FOR_CV_SEARCH = "SET_LONGITUDE_FOR_CV_SEARCH";
export const SET_SELECTED_LOCATION_FROM_GOOGLE_CV_SEARCH =
  "SET_SELECTED_LOCATION_FROM_GOOGLE_CV_SEARCH";
export const SET_CV_SEARCH_VIEWS = "SET_CV_SEARCH_VIEWS";
export const SET_IS_SWP_PROFILE_LOADING = "SET_IS_SWP_PROFILE_LOADING";
export const SET_CV_SEARCH_VIEWS_TOTAL = "SET_CV_SEARCH_VIEWS_TOTAL";

// Notificaitons
export const SET_NOTIFICATION_TOAST_LIST = "SET_NOTIFICATION_TOAST_LIST";
export const RESET_NOTIFCAITONS_REDUCER = "RESET_NOTIFCAITONS_REDUCER";

// Quotes
export const RESET_QUTOES_REDUCER = "RESET_QUTOES_REDUCER";
export const SET_SCREEN_TO_SHOW_ON_QUOTE = "SET_SCREEN_TO_SHOW_ON_QUOTE";
export const SET_ALL_QUOTES_DATA = "SET_ALL_QUOTES_DATA";
export const SET_EXPIRED_QUOTES_DATA = "SET_EXPIRED_QUOTES_DATA";
export const EXPIRED_API_LOADING = "EXPIRED_API_LOADING";
export const ALL_QUOTES_API_LOADING = "ALL_QUOTES_API_LOADING";
export const SET_CURRENT_PAGE_PAGINATION = "SET_CURRENT_PAGE_PAGINATION";
export const RESET_STATE = "RESET_STATE";

//Account Settings

export const SET_SCREEN_TO_SHOW_IN_SETTINGS = "SET_SCREEN_TO_SHOW_IN_SETTINGS";
export const RESET_ACCOUNT_SETTINGS = "RESET_ACCOUNT_SETTINGS";

// Oraganization

export const SET_IS_ORGANISATION_SELECTED = "SET_IS_ORGANISATION_SELECTED";
export const RESET_ORGANISATION_REDUCER = "RESET_ORGANISATION_REDUCER";
export const SET_ORGANISATION_ID = "SET_ORGANISATION_ID";
export const SET_ORGANISATION_MEMBERS = "SET_ORGANISATION_MEMBERS";
export const SET_ORGANISATION_IS_ACCOUNT_OWNER =
  "SET_ORGANISATION_IS_ACCOUNT_OWNER";
export const SET_ACTIVE_ORGANISATION_ID = "SET_ACTIVE_ORGANISATION_ID";
export const SET_USER_MENUS_ACCESS = "SET_USER_MENUS_ACCESS";
export const SET_IS_FULL_ACCESS = "SET_IS_FULL_ACCESS";
export const SET_ORGANISATION_SIZE = "SET_ORGANISATION_SIZE";
export const SET_ORGANISATION_FILTER = "SET_ORGANISATION_FILTER";
export const SET_IS_ORGANISATION_APPROVED = "SET_IS_ORGANISATION_APPROVED";
export const SET_HAS_OWNER_CONGRATULATED_FOR_APPROVAL =
  "SET_HAS_OWNER_CONGRATULATED_FOR_APPROVAL";
export const SET_ALL_ORGANISATIONS = "SET_ALL_ORGANISATIONS";
export const SET_ORGANISATION_ACCOUNT_OWNER_ID =
  "SET_ORGANISATION_ACCOUNT_OWNER_ID";
export const UPDATE_SELECTED_ORGANISATION_NAME =
  "UPDATE_SELECTED_ORGANISATION_NAME";
export const SET_MESSAGE_TEMPLATE = "SET_MESSAGE_TEMPLATE";
export const SET_SELECTED_MESSAGE_TEMPLATE = "SET_SELECTED_MESSAGE_TEMPLATE";
export const ADD_MESSAGE_TEMPLATE = "ADD_MESSAGE_TEMPLATE";
export const DELETE_MESSAGE_TEMPLATE = "DELETE_MESSAGE_TEMPLATE";
export const UPDATE_MESSAGE_TEMPLATE = "UPDATE_MESSAGE_TEMPLATE";
export const ALLOWED_EXTERNAL_LINK = "ALLOWED_EXTERNAL_LINK";
export const SHIFT_REQUEST_STATUS = "SHIFT_REQUEST_STATUS";

//Billing
export const SET_SHOW_BILLING_MODAL = "SET_SHOW_BILLING_MODAL";
export const SET_CURRENT_BILLING_MODAL_STEP = "SET_CURRENT_BILLING_MODAL_STEP";
export const SET_PLAN_INTERVAL_SWITCH_VALUE = "SET_PLAN_INTERVAL_SWITCH_VALUE";
export const SET_SELECTED_PLAN = "SET_SELECTED_PLAN";
export const SET_SELECTED_PAYMENT_METHOD = "SET_SELECTED_PAYMENT_METHOD";
export const SET_SELECTED_CARD_BRAND = "SET_SELECTED_CARD_BRAND";
export const SET_SELECTED_CARD_ENDING_IN = "SET_SELECTED_CARD_ENDING_IN";
export const SET_BILLING_PLAN = "SET_BILLING_PLAN";
export const SET_JOB_POSTING_LIMIT_END = "SET_JOB_POSTING_LIMIT_END";
export const SET_BUY_BOOST_MODAL = "SET_BUY_BOOST_MODAL";
export const SET_SHOW_CHANGE_CARD_MODAL = "SET_SHOW_CHANGE_CARD_MODAL";
export const SET_NEXT_PAYMENT_DATE = "SET_NEXT_PAYMENT_DATE";
export const SET_IS_CUSTOM_PLAN_AVAILABLE = "SET_IS_CUSTOM_PLAN_AVAILABLE";
export const SET_IS_PAYMENT_FAILED = "SET_IS_PAYMENT_FAILED";

export const RESET_BILLING_REDUCER = "RESET_BILLING_REDUCER";
export const SET_BOOST_MATCHING_CANDIDATES_LIST =
  "SET_BOOST_MATCHING_CANDIDATES_LIST";
export const SET_BOOST_JOB_ID = "SET_BOOST_JOB_ID";
export const SET_BOOST_JOB_ID_FOR_BADGE = "SET_BOOST_JOB_ID_FOR_BADGE";
export const SET_BOOST_CONFIRMATION_MODAL = "SET_BOOST_CONFIRMATION_MODAL";

export const SET_SHOW_JOB_POST_CALCULATOR = "SET_SHOW_JOB_POST_CALCULATOR";
export const SET_SHOW_JOB_BOOST_CALCULATOR = "SET_SHOW_JOB_BOOST_CALCULATOR";
export const SET_SHOW_CV_VIEWS_CALCULATOR = "SET_SHOW_CV_VIEWS_CALCULATOR";

export const SET_SELECTED_JOB_POST_CREDITS = "SET_SELECTED_JOB_POST_CREDITS";
export const SET_SELECTED_JOB_BOOST_CREDITS = "SET_SELECTED_JOB_BOOST_CREDITS";
export const SET_SELECTED_CV_VIEWS_CREDITS = "SET_SELECTED_CV_VIEWS_CREDITS";
export const SET_ORDER_CART = "SET_ORDER_CART";
export const SET_JOB_POST_MODAL = "SET_JOB_POST_MODAL";
export const ISPAYMENTVERIFYING = "ISPAYMENTVERIFYING";

//Shift
export const RESET_SHIFT_REDUCER = "RESET_SHIFT_REDUCER";
export const SET_SHOW_CREATE_ROLE = "SET_SHOW_CREATE_ROLE";
export const SET_CREATE_ROLE = "SET_CREATE_ROLE";
export const SET_SHIFT_POST_ACTIVE_STEPS = "SET_SHIFT_POST_ACTIVE_STEPS";

export const SET_ROLE_NAME = "SET_ROLE_NAME";
export const SET_ROLE_REFERENCE = "SET_ROLE_REFERENCE";
export const SET_ROLE_LICENSE = "SET_ROLE_LICENSE";
export const SET_ROLE_JOB_DESCRIPTION = "SET_ROLE_JOB_DESCRIPTION";
export const SET_ROLE_UNIFORM_TYPE = "SET_ROLE_UNIFORM_TYPE";
export const SET_ROLE_UNIFORM_DESCRIPTION = "SET_ROLE_UNIFORM_DESCRIPTION";
export const SET_ROLE_UNIFORM_IMAGE = "SET_ROLE_UNIFORM_IMAGE";
export const SET_ROLE_SITE_TYPE = "SET_ROLE_SITE_TYPE";
export const SET_ROLE_SITE_LIST = "SET_ROLE_SITE_LIST";
export const SET_DISCARD_MODAL_FOR_SHIFT_POST =
  "SET_DISCARD_MODAL_FOR_SHIFT_POST";
export const SET_SHIFT_POSTING_Array = "SET_SHIFT_POSTING_Array";
export const SET_SHIFT_POSTING_DELETE_Array = "SET_SHIFT_POSTING_DELETE_Array";
export const SET_SHIFT_SELECT_SITE = "SET_SHIFT_SELECT_SITE";
export const SET_SHIFT_SELECT_ROLE = "SET_SHIFT_SELECT_ROLE";
export const SET_SHIFT_SELECT_VENUE_TYPE = "SET_SHIFT_SELECT_VENUE_TYPE";
export const SET_SHIFT_CALCULATION = "SET_SHIFT_CALCULATION";
export const SET_SHIFT_EXTERNSL_CHARGES = "SET_SHIFT_EXTERNSL_CHARGES";
export const SET_SELECTED_CANDIDATES_FOR_OFFER =
  "SET_SELECTED_CANDIDATES_FOR_OFFER";
export const REMOVE_SELECTED_CANDIDATES_FOR_OFFER =
  "REMOVE_SELECTED_CANDIDATES_FOR_OFFER";
export const RESET_SELECTED_CANDIDATES_FOR_OFFER =
  "RESET_SELECTED_CANDIDATES_FOR_OFFER";

export const SET_CREATE_SITE = "SET_CREATE_SITE";
export const SET_SHOW_CREATE_SITE = "SET_SHOW_CREATE_SITE";
export const SET_SITE_NAME = "SET_SITE_NAME";
export const SET_SITE_REFERENCE = "SET_SITE_REFERENCE";
export const SET_SITE_ADDRESS1 = "SET_SITE_ADDRESS1";
export const SET_SITE_ADDRESS2 = "SET_SITE_ADDRESS2";
export const SET_SITE_POSTCODE = "SET_SITE_POSTCODE";
export const SET_SITE_CITY = "SET_SITE_CITY";
export const SET_SITE_ACCESS_INSTRUCTION = "SET_SITE_ACCESS_INSTRUCTION";
export const SET_SITE_LABEL_COLOR = "SET_SITE_LABEL_COLOR";
export const SET_SITE_CONTACT_PERSON = "SET_SITE_CONTACT_PERSON";
export const SET_SITE_CONTACT_NUMBER = "SET_SITE_CONTACT_NUMBER";
export const SET_SITE_USE_MY_DETAIL = "SET_SITE_USE_MY_DETAIL";
export const SET_CURRENT_STEP_WORKER_SCREEN = "SET_CURRENT_STEP_WORKER_SCREEN";
export const SHOW_WORKER_SCREEN = "SHOW_WORKER_SCREEN";
